const maleMeasurements=[
 ["قد پیراهن","qadPirahan"],["شانه","shana"],["آستین","astin"],["بغل","baghal"],["بر دامن","barDaman"],["قد شلوار","qadShalwar"],["بر تنبان","barTanban"],["پاچه","pacha"],["یخن","yakhon"],["بر یخن","barYakhon"],["کف","kaf"],["دهن آستین","dehanAstin"]
];
const femaleMeasurements=[
 ["قد پیراهن","qadPirahan"],["شانه","shana"],["آستین","astin"],["بغل","baghal"],["کمر","kamar"],["بالاتنه","balaTana"],["سورین","sorin"],["قد کرتی","qadKarti"],["قد واسکت","qadVasakat"],["قد دامن","qadDaman"],["قد شلوار","qadShalwar"],["بر دامن","barDaman"],["پاچه","pacha"],["بر یخن","barYakhon"],["دهن آستین","dehanAstin"]
];
const statusNames={registered:"ثبت‌شده",cutting:"برش",sewing:"دوخت",fitting:"پرو",ready:"آماده",delivered:"تحویل‌شده",cancelled:"لغو‌شده"};
const expenseNames={rent:"کرایه",electricity:"برق",fabric:"پارچه",sewing:"لوازم خیاطی",transport:"حمل‌ونقل",food:"خوراک",salary:"حقوق",other:"سایر"};
let customerFormMode="create";
const $=id=>document.getElementById(id);
function money(n){return new Intl.NumberFormat("fa-AF").format(Math.round(Number(n||0)))}
function qty(n){return new Intl.NumberFormat("fa-AF",{maximumFractionDigits:2}).format(Number(n||0))}
function dateText(d){if(!d)return "-";return new Date(d).toLocaleDateString("fa-AF")}
function todayISO(){return new Date().toISOString().slice(0,10)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function getToken(){return localStorage.getItem("khayyat_token")||""}
async function api(url,options={}){const token=getToken(),headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization="Bearer "+token;const res=await fetch(url,{...options,headers});let data={};try{data=await res.json()}catch{}if(res.status===401&&!url.startsWith("/api/auth/")){logout(false);throw new Error("لطفاً دوباره وارد شوید")};if(!res.ok)throw new Error(data.error||"خطا در ارتباط با سرور");return data}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}

function showAuthError(msg){const e=$("authError");e.textContent=msg;e.classList.toggle("show",!!msg)}
function showAuthTab(tab){const login=tab==="login";$("loginForm").classList.toggle("hidden",!login);$("registerForm").classList.toggle("hidden",login);$("loginTab").classList.toggle("active",login);$("registerTab").classList.toggle("active",!login);showAuthError("")}
async function login(e){e.preventDefault();showAuthError("");try{const d=await authFetch("/api/auth/login",{username:$("loginUsername").value,password:$("loginPassword").value});localStorage.setItem("khayyat_token",d.token);localStorage.setItem("khayyat_user",JSON.stringify(d.user));enterApp(d.user)}catch(err){showAuthError(err.message)}}
async function register(e){e.preventDefault();showAuthError("");if($("regPassword").value!==$("regPassword2").value){showAuthError("تکرار رمز عبور یکسان نیست");return}try{const d=await authFetch("/api/auth/register",{name:$("regName").value,username:$("regUsername").value,password:$("regPassword").value});localStorage.setItem("khayyat_token",d.token);localStorage.setItem("khayyat_user",JSON.stringify(d.user));enterApp(d.user)}catch(err){showAuthError(err.message)}}
async function authFetch(url,body){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"خطا");return d}
function enterApp(user){$("authScreen").classList.add("hidden");$("appShell").classList.remove("hidden");$("currentUser").textContent=user?.name||user?.username||"";$("settingsUser").textContent=user?.name?`${user.name} (${user.username})`:user?.username||"-";refreshAll()}
function logout(show=true){localStorage.removeItem("khayyat_token");localStorage.removeItem("khayyat_user");$("appShell").classList.add("hidden");$("authScreen").classList.remove("hidden");if(show){$("loginForm").reset();showAuthTab("login")}}
async function bootAuth(){if(!getToken()){logout(false);return}try{const d=await api("/api/auth/me");enterApp(d.user)}catch{logout(false)}}

function goHome(){closeAllModals();showPage("dashboard");history.replaceState({page:"dashboard"},"",location.pathname+location.search)}
function closeAllModals(){document.querySelectorAll(".modal").forEach(x=>x.classList.add("hidden"));document.querySelectorAll(".form-card").forEach(x=>x.classList.add("hidden"))}
function showPage(page){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("page-"+page).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));window.scrollTo({top:0,behavior:"smooth"});if(page==="dashboard")loadDashboard();if(page==="customers")loadCustomers();if(page==="orders")loadOrders();if(page==="expenses")loadExpenses();if(page==="employees")loadEmployees();if(page==="inventory")loadInventory();if(page==="reports")loadReports()}
function closeModal(id){$(id).classList.add("hidden")}
function openModal(id){$(id).classList.remove("hidden")}

function renderMeasurements(values={}){const gender=$("cGender").value,list=gender==="female"?femaleMeasurements:maleMeasurements;$("measurements").innerHTML=`<div class="measurement-title">اندازه ${gender==="female"?"زن":"مرد"}</div>`+list.map(([label,key])=>`<label>${label}<input type="number" step="0.1" min="0" data-measure="${key}" value="${values[key]??""}" inputmode="decimal"></label>`).join("")}
function getMeasurements(){const values={};document.querySelectorAll("[data-measure]").forEach(i=>{if(i.value!=="")values[i.dataset.measure]=Number(i.value)});return{unit:$("mUnit").value,values}}
function openNewCustomer(){ customerFormMode="create";$("customerModalTitle").textContent="مشتری و سفارش جدید";$("customerForm").reset();$("customerId").value="";$("mUnit").value="cm";$("oPaid").value=0;$("oDiscount").value=0;$("oStatus").value="registered";renderMeasurements();openModal("customerModal") }
async function saveCustomer(e){
  e.preventDefault();
  const gender=$("cGender").value||"male";
  const n=v=>{const x=Number(v);return Number.isFinite(x)&&x>=0?x:0};
  const order={description:$("oDescription").value||"",price:n($("oPrice").value),discount:n($("oDiscount").value),initialPaid:n($("oPaid").value),dueDate:$("oDue").value||null,status:$("oStatus").value||"registered",notes:$("oNotes").value||""};
  const customer={name:$("cName").value.trim(),phone:$("cPhone").value||"",address:$("cAddress").value||"",gender,notes:$("cNotes").value||"",measurements:{[gender]:getMeasurements()}};
  try{
    if(customerFormMode==="order"){
      const customerId=$("customerId").value;
      if(!customerId)throw new Error("شناسه مشتری پیدا نشد");
      await api("/api/orders",{method:"POST",body:JSON.stringify({customerId,...order})});
      toast("سفارش با موفقیت ثبت شد");
    }else if(customerFormMode==="edit"){
      const id=$("customerId").value;
      await api("/api/customers/"+id,{method:"PUT",body:JSON.stringify({...customer,order})});
      toast("مشتری، اندازه و سفارش با موفقیت ذخیره شد");
    }else{
      const result=await api("/api/customers",{method:"POST",body:JSON.stringify({...customer,order})});
      if(!result.order || !result.order._id)throw new Error("سفارش در سرور ایجاد نشد");
      toast("مشتری و سفارش با موفقیت ثبت شد");
    }
    closeModal("customerModal");
    await refreshAll();
    showPage("orders");
  }catch(err){toast("ذخیره انجام نشد: "+err.message)}
}

async function loadDashboard(){try{const d=await api("/api/dashboard");$("dbStatus").textContent="● آنلاین";$("dbStatus").classList.remove("off");$("sCustomers").textContent=money(d.customers);$("sActive").textContent=money(d.activeOrders);$("sTodayReceived").textContent=money(d.todayReceived);$("sTodayExpense").textContent=money(d.todayExpenses);$("sReceivable").textContent=money(d.totalReceivable);$("sProfit").textContent=money(d.approximateProfit);$("sSales").textContent=money(d.totalSales);$("sReceived").textContent=money(d.totalReceived);$("sExpenses").textContent=money(d.totalExpenses);$("sEmployees").textContent=money(d.activeEmployees);$("sPayroll").textContent=money(d.monthlyPayrollRemaining);$("sInventoryItems").textContent=money(d.inventoryItems);$("sInventoryValue").textContent=money(d.inventoryValue);$("sLowStock").textContent=money(d.lowStock)}catch(e){$("dbStatus").textContent="● قطع";$("dbStatus").classList.add("off");toast(e.message)}}

async function loadCustomers(){try{const list=await api("/api/customers?q="+encodeURIComponent($("customerSearch").value||""));$("customerList").innerHTML=list.length?list.map(c=>`<div class="list-card"><div class="row"><div><div class="name">${esc(c.name)}</div><div class="muted">${esc(c.phone||"بدون شماره")}</div></div><span class="badge">${c.gender==="female"?"زن":"مرد"}</span></div><div class="muted">${esc(c.address||"")}</div><div class="actions"><button onclick="viewCustomer('${c._id}')">مشاهده</button><button onclick="editCustomer('${c._id}')">ویرایش</button><button onclick="newOrderFor('${c._id}')">＋ سفارش</button><button class="danger" onclick="deleteCustomer('${c._id}')">حذف</button></div></div>`).join(""):'<div class="empty">مشتری پیدا نشد.</div>'}catch(e){toast(e.message)}}
async function viewCustomer(id){
  try{
    const d=await api("/api/customers/"+id), c=d.customer, g=c.gender, m=c.measurements?.[g];
    const defs=g==="female"?femaleMeasurements:maleMeasurements;
    const ms=defs.map(([l,k])=>`<div class="detail-item"><small>${l}</small><b>${m?.values?.[k]??"-"} ${m?.values?.[k]!=null?(m.unit==="inch"?"اینچ":"سانتی‌متر"):""}</b></div>`).join("");
    const ordersHtml=d.orders.length?d.orders.map(orderCard).join(""):"<div class=\"empty\">سفارشی ثبت نشده.</div>";
    $("customerView").innerHTML=`<div class="card"><div class="row"><div><h3>${esc(c.name)}</h3><p class="muted">${g==="female"?"مشتری زن":"مشتری مرد"}</p></div><span class="badge">${g==="female"?"زن":"مرد"}</span></div><p>📞 ${esc(c.phone||"-")}<br>📍 ${esc(c.address||"-")}</p></div><div class="card"><h3>اندازه ${g==="female"?"زن":"مرد"} — فقط همین گروه</h3><div class="detail-grid">${ms}</div></div><div class="card"><h3>سفارش‌ها</h3>${ordersHtml}</div>`;
    openModal("customerViewModal");
  }catch(e){toast(e.message)}
}
function orderCard(o){return`<div class="list-card"><div class="row"><b>${esc(o.description||"بدون شرح")}</b><span class="badge">${statusNames[o.status]||o.status}</span></div><div class="muted">ثبت: ${dateText(o.createdAt)}${o.dueDate?" | تحویل: "+dateText(o.dueDate):""}</div><div class="finance-row"><span>قابل پرداخت</span><b>${money(o.totals.gross)} افغانی</b></div><div class="finance-row"><span>دریافت</span><b>${money(o.totals.paid)} افغانی</b></div><div class="finance-row"><span>باقی‌مانده</span><b>${money(o.totals.remaining)} افغانی</b></div><div class="actions"><button onclick="openPayment('${o._id}',${o.totals.remaining})">＋ پرداخت</button><button class="danger" onclick="deleteOrder('${o._id}')">حذف</button></div></div>`}
async function editCustomer(id){try{customerFormMode="edit";const d=await api("/api/customers/"+id),c=d.customer,m=c.measurements?.[c.gender];$("customerModalTitle").textContent="ویرایش مشتری";$("customerId").value=c._id;$("cName").value=c.name;$("cPhone").value=c.phone||"";$("cAddress").value=c.address||"";$("cGender").value=c.gender;$("cNotes").value=c.notes||"";$("mUnit").value=m?.unit||"cm";renderMeasurements(m?.values||{});const o=d.orders[0];$("oDescription").value=o?.description||"";$("oPrice").value=o?.price||"";$("oDiscount").value=o?.discount||0;$("oPaid").value=o?.initialPaid||0;$("oDue").value=o?.dueDate?o.dueDate.slice(0,10):"";$("oStatus").value=o?.status||"registered";$("oNotes").value=o?.notes||"";openModal("customerModal")}catch(e){toast(e.message)}}
async function newOrderFor(id){
  try{customerFormMode="order";
    const d=await api("/api/customers/"+id),c=d.customer;
    $("customerModalTitle").textContent="ثبت سفارش جدید برای مشتری";
    $("customerId").value=c._id;$("cName").value=c.name||"";$("cPhone").value=c.phone||"";$("cAddress").value=c.address||"";$("cGender").value=c.gender||"male";$("cNotes").value=c.notes||"";
    const m=c.measurements?.[c.gender];$("mUnit").value=m?.unit||"cm";renderMeasurements(m?.values||{});
    $("oDescription").value="";$("oPrice").value="";$("oDiscount").value=0;$("oPaid").value=0;$("oDue").value="";$("oStatus").value="registered";$("oNotes").value="";
    openModal("customerModal");
  }catch(e){toast(e.message)}
}
async function deleteCustomer(id){if(!confirm("مشتری و تمام سفارش‌های او حذف شود؟"))return;try{await api("/api/customers/"+id,{method:"DELETE"});toast("مشتری حذف شد");loadCustomers();loadDashboard()}catch(e){toast(e.message)}}

async function loadOrders(){try{const list=await api("/api/orders?q="+encodeURIComponent($("orderSearch").value||""));$("orderList").innerHTML=list.length?list.map(o=>`<div class="list-card"><div class="row"><div><div class="name">${esc(o.customerId?.name||"مشتری حذف‌شده")}</div><div class="muted">${esc(o.description||"بدون شرح")}</div></div><span class="badge">${statusNames[o.status]||o.status}</span></div><div class="finance-row"><span>مبلغ</span><b>${money(o.totals.gross)} افغانی</b></div><div class="finance-row"><span>باقی‌مانده</span><b>${money(o.totals.remaining)} افغانی</b></div><div class="actions"><button onclick="openPayment('${o._id}',${o.totals.remaining})">＋ پرداخت</button><button onclick="changeStatus('${o._id}','${o.status}')">تغییر وضعیت</button><button class="danger" onclick="deleteOrder('${o._id}')">حذف</button></div></div>`).join(""):'<div class="empty">سفارشی پیدا نشد.</div>'}catch(e){toast(e.message)}}
async function changeStatus(id,current){const keys=Object.keys(statusNames),idx=keys.indexOf(current),next=keys[(idx+1)%keys.length];try{await api("/api/orders/"+id,{method:"PUT",body:JSON.stringify({status:next})});toast("وضعیت تغییر کرد");loadOrders();loadDashboard()}catch(e){toast(e.message)}}
function openPayment(id,remaining){if(remaining<=0){toast("این سفارش تسویه شده است");return}$("paymentOrderId").value=id;$("paymentAmount").value=remaining;$("paymentNote").value="";openModal("paymentModal")}
async function savePayment(){try{await api("/api/orders/"+$("paymentOrderId").value+"/payments",{method:"POST",body:JSON.stringify({amount:Number($("paymentAmount").value),note:$("paymentNote").value})});closeModal("paymentModal");toast("پرداخت ثبت شد");loadOrders();loadDashboard()}catch(e){toast(e.message)}}
async function deleteOrder(id){if(!confirm("این سفارش حذف شود؟"))return;try{await api("/api/orders/"+id,{method:"DELETE"});toast("سفارش حذف شد");loadOrders();loadDashboard()}catch(e){toast(e.message)}}

function openExpenseForm(expense=null){$("expenseForm").classList.remove("hidden");$("expenseId").value=expense?._id||"";$("expenseFormTitle").textContent=expense?"ویرایش هزینه":"ثبت هزینه";$("expenseDate").value=expense?expense.date.slice(0,10):todayISO();$("expenseType").value=expense?.type||"other";$("expensePerson").value=expense?.person||"";$("expenseAmount").value=expense?.amount||"";$("expenseDescription").value=expense?.description||"";window.scrollTo({top:0,behavior:"smooth"})}
function closeExpenseForm(){$("expenseForm").classList.add("hidden")}
async function saveExpense(){const payload={date:$("expenseDate").value,type:$("expenseType").value,person:$("expensePerson").value,amount:Number($("expenseAmount").value),description:$("expenseDescription").value};try{const id=$("expenseId").value;await api(id?"/api/expenses/"+id:"/api/expenses",{method:id?"PUT":"POST",body:JSON.stringify(payload)});closeExpenseForm();toast("هزینه ذخیره شد");loadExpenses();loadDashboard()}catch(e){toast(e.message)}}
async function loadExpenses(){try{const list=await api("/api/expenses");$("expenseTotal").textContent=money(list.reduce((s,e)=>s+Number(e.amount||0),0));$("expenseList").innerHTML=list.length?list.map(e=>`<div class="list-card"><div class="row"><div><b>${expenseNames[e.type]||e.type}</b><div class="muted">${dateText(e.date)} | انجام‌دهنده: ${esc(e.person||"-")}</div></div><b>${money(e.amount)} افغانی</b></div><div class="muted">${esc(e.description||"")}</div><div class="actions"><button onclick='openExpenseForm(${JSON.stringify(e).replace(/'/g,"&#39;")})'>ویرایش</button><button class="danger" onclick="deleteExpense('${e._id}')">حذف</button></div></div>`).join(""):'<div class="empty">هزینه‌ای ثبت نشده.</div>'}catch(e){toast(e.message)}}
async function deleteExpense(id){if(!confirm("این هزینه حذف شود؟"))return;try{await api("/api/expenses/"+id,{method:"DELETE"});toast("هزینه حذف شد");loadExpenses();loadDashboard()}catch(e){toast(e.message)}}

function openEmployeeForm(e=null){$("employeeModalTitle").textContent=e?"ویرایش کارمند":"ثبت کارمند";$("employeeId").value=e?e._id:"";$("eName").value=e?.name||"";$("ePhone").value=e?.phone||"";$("eTask").value=e?.task||"";$("eSalary").value=e?.monthlySalary||"";$("eStart").value=e?.startDate?e.startDate.slice(0,10):todayISO();$("eStatus").value=e?.status||"active";$("eNotes").value=e?.notes||"";openModal("employeeModal")}
async function saveEmployee(){const p={name:$("eName").value,phone:$("ePhone").value,task:$("eTask").value,monthlySalary:Number($("eSalary").value||0),startDate:$("eStart").value,status:$("eStatus").value,notes:$("eNotes").value};try{const id=$("employeeId").value;await api(id?"/api/employees/"+id:"/api/employees",{method:id?"PUT":"POST",body:JSON.stringify(p)});closeModal("employeeModal");toast(id?"کارمند ویرایش شد":"کارمند ثبت شد");loadEmployees();loadDashboard()}catch(e){toast(e.message)}}
async function editEmployee(id){try{const list=await api("/api/employees"),e=list.find(x=>x._id===id);if(!e)throw new Error("کارمند پیدا نشد");openEmployeeForm(e)}catch(e){toast(e.message)}}
async function loadEmployees(){try{const list=await api("/api/employees");const total=list.reduce((s,e)=>s+Number(e.payroll.salary),0),paid=list.reduce((s,e)=>s+Number(e.payroll.paid),0),remaining=list.reduce((s,e)=>s+Number(e.payroll.remaining),0);$("empTotalSalary").textContent=money(total)+" افغانی";$("empPaid").textContent=money(paid)+" افغانی";$("empRemaining").textContent=money(remaining)+" افغانی";$("employeeList").innerHTML=list.length?list.map(e=>`<div class="employee-card list-card"><div class="row"><div><div class="name">${esc(e.name)}</div><div class="muted">${esc(e.task||"بدون وظیفه مشخص")}</div></div><span class="badge ${e.status==='inactive'?'gray':''}">${e.status==='active'?'فعال':'غیرفعال'}</span></div><div class="employee-meta"><span>حقوق ماهانه<strong>${money(e.payroll.salary)}</strong></span><span>پرداخت‌شده<strong class="paid">${money(e.payroll.paid)}</strong></span><span>باقی‌مانده<strong class="due">${money(e.payroll.remaining)}</strong></span></div><div class="muted">📞 ${esc(e.phone||"-" )} | شروع: ${dateText(e.startDate)}</div><div class="actions"><button onclick="editEmployee('${e._id}')">ویرایش</button><button class="primary" onclick="openEmployeePay('${e._id}',${e.payroll.remaining})">پرداخت حقوق</button><button class="danger" onclick="deleteEmployee('${e._id}')">حذف</button></div></div>`).join(""):'<div class="empty">هنوز کارمندی ثبت نشده است.</div>'}catch(e){toast(e.message)}}
async function openEmployeePay(id,remaining){try{const list=await api("/api/employees"),e=list.find(x=>x._id===id);$("payEmployeeId").value=id;$("payEmployeeInfo").innerHTML=`<b>${esc(e?.name||"کارمند")}</b><br>باقی حقوق این ماه: <strong>${money(remaining)} افغانی</strong>`;$("employeePayAmount").value=remaining||"";$("employeePayDate").value=todayISO();$("employeePayNote").value="";openModal("employeePayModal")}catch(e){toast(e.message)}}
async function saveEmployeePayment(){try{await api("/api/employees/"+$("payEmployeeId").value+"/payments",{method:"POST",body:JSON.stringify({amount:Number($("employeePayAmount").value),date:$("employeePayDate").value,note:$("employeePayNote").value})});closeModal("employeePayModal");toast("پرداخت حقوق ثبت شد");loadEmployees();loadDashboard()}catch(e){toast(e.message)}}
async function deleteEmployee(id){if(!confirm("این کارمند حذف شود؟ سابقه پرداخت‌های او نیز حذف خواهد شد."))return;try{await api("/api/employees/"+id,{method:"DELETE"});toast("کارمند حذف شد");loadEmployees();loadDashboard()}catch(e){toast(e.message)}}

function openInventoryForm(i=null){$("inventoryModalTitle").textContent=i?"ویرایش کالا":"ثبت کالا";$("inventoryId").value=i?i._id:"";$("iName").value=i?.name||"";$("iCategory").value=i?.category||"";$("iQuantity").value=i?.quantity||0;$("iUnit").value=i?.unit||"عدد";$("iMinStock").value=i?.minStock||0;$("iUnitPrice").value=i?.unitPrice||0;$("iNotes").value=i?.notes||"";$("iQuantity").disabled=!!i;openModal("inventoryModal")}
async function saveInventory(){const id=$("inventoryId").value,p={name:$("iName").value,category:$("iCategory").value,quantity:Number($("iQuantity").value||0),unit:$("iUnit").value,minStock:Number($("iMinStock").value||0),unitPrice:Number($("iUnitPrice").value||0),notes:$("iNotes").value};try{await api(id?"/api/inventory/"+id:"/api/inventory",{method:id?"PUT":"POST",body:JSON.stringify(p)});closeModal("inventoryModal");toast(id?"کالا ویرایش شد":"کالا به موجودی اضافه شد");loadInventory();loadDashboard()}catch(e){toast(e.message)}}
async function editInventory(id){try{const list=await api("/api/inventory"),i=list.find(x=>x._id===id);if(!i)throw new Error("کالا پیدا نشد");openInventoryForm(i)}catch(e){toast(e.message)}}
async function loadInventory(){try{const list=await api("/api/inventory");const q=($("inventorySearch").value||"").toLowerCase();const filtered=q?list.filter(i=>i.name.toLowerCase().includes(q)||(i.category||"").toLowerCase().includes(q)):list;$("invTotalValue").textContent=money(list.reduce((s,i)=>s+i.totalValue,0))+" افغانی";$("invLow").textContent=money(list.filter(i=>i.lowStock).length);$("inventoryList").innerHTML=filtered.length?filtered.map(i=>`<div class="inventory-card list-card ${i.lowStock?'low-stock':''}"><div class="row"><div><div class="name">${esc(i.name)}</div><div class="muted">${esc(i.category||"سایر")}</div></div><span class="badge ${i.lowStock?'danger-badge':''}">${i.lowStock?'کمبود موجودی':'موجود'}</span></div><div class="inventory-numbers"><div><small>مقدار</small><strong>${qty(i.quantity)} ${esc(i.unit)}</strong></div><div><small>قیمت واحد</small><strong>${money(i.unitPrice)}</strong></div><div><small>ارزش</small><strong>${money(i.totalValue)}</strong></div></div><div class="muted">حداقل موجودی: ${qty(i.minStock)} ${esc(i.unit)}</div><div class="actions"><button class="primary" onclick="openStock('${i._id}')">＋/− موجودی</button><button onclick="editInventory('${i._id}')">ویرایش</button><button class="danger" onclick="deleteInventory('${i._id}')">حذف</button></div></div>`).join(""):'<div class="empty">کالایی پیدا نشد.</div>'}catch(e){toast(e.message)}}
async function openStock(id){try{const list=await api("/api/inventory"),i=list.find(x=>x._id===id);$("stockId").value=id;$("stockInfo").innerHTML=`<b>${esc(i?.name||"کالا")}</b><br>موجودی فعلی: <strong>${qty(i?.quantity)} ${esc(i?.unit||"")}</strong>`;$("stockType").value="in";$("stockQuantity").value="";$("stockDate").value=todayISO();$("stockNote").value="";openModal("stockModal")}catch(e){toast(e.message)}}
async function saveStockMovement(){try{await api("/api/inventory/"+$("stockId").value+"/movement",{method:"POST",body:JSON.stringify({type:$("stockType").value,quantity:Number($("stockQuantity").value),date:$("stockDate").value,note:$("stockNote").value})});closeModal("stockModal");toast("موجودی به‌روزرسانی شد");loadInventory();loadDashboard()}catch(e){toast(e.message)}}
async function deleteInventory(id){if(!confirm("این کالا از موجودی حذف شود؟"))return;try{await api("/api/inventory/"+id,{method:"DELETE"});toast("کالا حذف شد");loadInventory();loadDashboard()}catch(e){toast(e.message)}}

async function loadReports(){try{const d=await api("/api/dashboard"),orders=await api("/api/orders");$("rSales").textContent=money(d.totalSales);$("rReceived").textContent=money(d.totalReceived);$("rReceivable").textContent=money(d.totalReceivable);$("rExpenses").textContent=money(d.totalExpenses);$("rProfit").textContent=money(d.approximateProfit);$("rActive").textContent=money(d.activeOrders);const counts={};orders.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);$("statusReport").innerHTML=Object.keys(statusNames).map(k=>`<div class="finance-row"><span>${statusNames[k]}</span><b>${counts[k]||0}</b></div>`).join("")}catch(e){toast(e.message)}}
async function refreshAll(){await Promise.all([loadDashboard(),loadCustomers(),loadOrders(),loadExpenses(),loadEmployees(),loadInventory(),loadReports()])}
window.addEventListener("popstate",()=>{if(!getToken())return;closeAllModals();goHome()});
window.addEventListener("keydown",e=>{if(e.key==="Escape"){closeAllModals();return}if((e.altKey&&e.key==="ArrowLeft")||e.key==="BrowserBack"){e.preventDefault();goHome()}});
document.addEventListener("DOMContentLoaded",()=>{renderMeasurements();history.replaceState({page:"dashboard"},"",location.pathname+location.search);bootAuth()});
