require("dotenv").config();
const express=require("express");
const mongoose=require("mongoose");
const cors=require("cors");
const path=require("path");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");

const app=express();
app.use(cors());
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:true}));
const PORT=process.env.PORT||3000;
const MONGODB_URI=process.env.MONGODB_URI;
const JWT_SECRET=process.env.JWT_SECRET||"CHANGE_THIS_SECRET_IN_PRODUCTION";
mongoose.set("strictQuery",true);

const userSchema=new mongoose.Schema({
  name:{type:String,required:true,trim:true},username:{type:String,required:true,unique:true,lowercase:true,trim:true,minlength:3},passwordHash:{type:String,required:true}
},{timestamps:true});
const paymentSchema=new mongoose.Schema({amount:{type:Number,required:true,min:0},date:{type:Date,default:Date.now},note:{type:String,default:""}},{_id:true});
const measurementSchema=new mongoose.Schema({unit:{type:String,enum:["cm","inch"],default:"cm"},values:{type:mongoose.Schema.Types.Mixed,default:{}}},{_id:false});
const customerSchema=new mongoose.Schema({
  ownerId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true},name:{type:String,required:true,trim:true},phone:{type:String,default:"",trim:true},address:{type:String,default:""},gender:{type:String,enum:["male","female"],default:"male"},notes:{type:String,default:""},
  measurements:{male:{type:measurementSchema,default:undefined},female:{type:measurementSchema,default:undefined}}
},{timestamps:true});
const orderSchema=new mongoose.Schema({
  ownerId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true},customerId:{type:mongoose.Schema.Types.ObjectId,ref:"Customer",required:true},description:{type:String,default:""},price:{type:Number,min:0,default:0},discount:{type:Number,min:0,default:0},initialPaid:{type:Number,min:0,default:0},payments:{type:[paymentSchema],default:[]},status:{type:String,enum:["registered","cutting","sewing","fitting","ready","delivered","cancelled"],default:"registered"},dueDate:{type:Date,default:null},notes:{type:String,default:""}
},{timestamps:true});
const expenseSchema=new mongoose.Schema({
  ownerId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true},date:{type:Date,default:Date.now},type:{type:String,enum:["rent","electricity","fabric","sewing","transport","food","salary","other"],default:"other"},description:{type:String,default:""},person:{type:String,default:""},amount:{type:Number,min:0,required:true}
},{timestamps:true});
const employeeSchema=new mongoose.Schema({
  ownerId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true},name:{type:String,required:true,trim:true},phone:{type:String,default:""},task:{type:String,default:""},monthlySalary:{type:Number,min:0,default:0},startDate:{type:Date,default:Date.now},status:{type:String,enum:["active","inactive"],default:"active"},notes:{type:String,default:""},payments:{type:[paymentSchema],default:[]}
},{timestamps:true});
const inventoryMovementSchema=new mongoose.Schema({type:{type:String,enum:["in","out"],required:true},quantity:{type:Number,min:0.0001,required:true},date:{type:Date,default:Date.now},note:{type:String,default:""}},{_id:true});
const inventorySchema=new mongoose.Schema({
  ownerId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true},name:{type:String,required:true,trim:true},category:{type:String,default:"سایر"},quantity:{type:Number,min:0,default:0},unit:{type:String,default:"عدد"},minStock:{type:Number,min:0,default:0},unitPrice:{type:Number,min:0,default:0},notes:{type:String,default:""},movements:{type:[inventoryMovementSchema],default:[]}
},{timestamps:true});
const User=mongoose.model("User",userSchema),Customer=mongoose.model("Customer",customerSchema),Order=mongoose.model("Order",orderSchema),Expense=mongoose.model("Expense",expenseSchema),Employee=mongoose.model("Employee",employeeSchema),Inventory=mongoose.model("Inventory",inventorySchema);

const oid=id=>mongoose.Types.ObjectId.isValid(id);
const tokenFor=u=>jwt.sign({id:u._id.toString()},JWT_SECRET,{expiresIn:"30d"});
const safeUser=u=>({id:u._id,name:u.name,username:u.username,createdAt:u.createdAt});
const dayKey=d=>new Date(d).toISOString().slice(0,10);
const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`};
function orderTotals(o){const gross=Math.max(0,Number(o.price||0)-Number(o.discount||0));const extra=(o.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0);const paid=Number(o.initialPaid||0)+extra;return {gross,paid,remaining:Math.max(0,gross-paid)}}
function employeePayroll(e,at=new Date()){const mk=monthKey(at);const paid=(e.payments||[]).filter(p=>monthKey(p.date)===mk).reduce((s,p)=>s+Number(p.amount||0),0);const salary=Number(e.monthlySalary||0);return {month:mk,salary,paid,remaining:Math.max(0,salary-paid)}}
function inventoryValue(i){return Number(i.quantity||0)*Number(i.unitPrice||0)}
async function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"ورود لازم است"});const d=jwt.verify(h.slice(7),JWT_SECRET);const u=await User.findById(d.id);if(!u)return res.status(401).json({error:"کاربر معتبر نیست"});req.user=u;next()}catch(e){res.status(401).json({error:"جلسه ورود معتبر نیست؛ دوباره وارد شوید"})}}
function ownFilter(req,id){return {_id:id,ownerId:req.user._id}}

app.get("/api/health",(req,res)=>res.json({ok:true,database:mongoose.connection.readyState===1}));
app.post("/api/auth/register",async(req,res)=>{try{const name=(req.body.name||"").trim(),username=(req.body.username||"").trim().toLowerCase(),password=req.body.password||"";if(name.length<2)return res.status(400).json({error:"نام حداقل ۲ حرف باشد"});if(!/^[a-z0-9_.-]{3,30}$/.test(username))return res.status(400).json({error:"نام کاربری باید ۳ تا ۳۰ کاراکتر انگلیسی باشد"});if(password.length<6)return res.status(400).json({error:"رمز عبور حداقل ۶ کاراکتر باشد"});if(await User.findOne({username}))return res.status(409).json({error:"این نام کاربری قبلاً ثبت شده است"});const u=await User.create({name,username,passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:tokenFor(u),user:safeUser(u)})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{const username=(req.body.username||"").trim().toLowerCase(),password=req.body.password||"",u=await User.findOne({username});if(!u||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({error:"نام کاربری یا رمز عبور نادرست است"});res.json({token:tokenFor(u),user:safeUser(u)})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/auth/me",auth,(req,res)=>res.json({user:safeUser(req.user)}));

app.get("/api/dashboard",auth,async(req,res)=>{try{const ownerId=req.user._id;const [orders,expenses,customers,employees,inventory]=await Promise.all([Order.find({ownerId}).lean(),Expense.find({ownerId}).lean(),Customer.countDocuments({ownerId}),Employee.find({ownerId}).lean(),Inventory.find({ownerId}).lean()]);const delivered=orders.filter(o=>o.status==="delivered"),active=orders.filter(o=>!['delivered','cancelled'].includes(o.status));const totalSales=delivered.reduce((s,o)=>s+orderTotals(o).gross,0),totalReceived=orders.reduce((s,o)=>s+orderTotals(o).paid,0),totalReceivable=orders.reduce((s,o)=>s+orderTotals(o).remaining,0),totalExpenses=expenses.reduce((s,e)=>s+Number(e.amount||0),0),inventoryValueTotal=inventory.reduce((s,i)=>s+inventoryValue(i),0);const today=dayKey(new Date()),todayExpenses=expenses.filter(e=>dayKey(e.date)===today).reduce((s,e)=>s+Number(e.amount||0),0);const todayReceived=orders.reduce((s,o)=>{let v=dayKey(o.createdAt)===today?Number(o.initialPaid||0):0;for(const p of o.payments||[])if(dayKey(p.date)===today)v+=Number(p.amount||0);return s+v},0);const payroll=employees.reduce((s,e)=>s+employeePayroll(e).remaining,0);const lowStock=inventory.filter(i=>Number(i.quantity)<=Number(i.minStock||0)).length;res.json({customers,orders:orders.length,activeOrders:active.length,totalSales,totalReceived,totalReceivable,totalExpenses,approximateProfit:totalSales-totalExpenses,todayExpenses,todayReceived,employees:employees.length,activeEmployees:employees.filter(e=>e.status==='active').length,monthlyPayrollRemaining:payroll,inventoryItems:inventory.length,inventoryValue:inventoryValueTotal,lowStock})}catch(e){res.status(500).json({error:e.message})}});

// Customers and orders
app.get("/api/customers",auth,async(req,res)=>{try{const q=(req.query.q||"").trim(),f={ownerId:req.user._id};if(q)f.$or=[{name:{$regex:q,$options:"i"}},{phone:{$regex:q,$options:"i"}}];res.json(await Customer.find(f).sort({createdAt:-1}).lean())}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/customers/:id",auth,async(req,res)=>{try{if(!oid(req.params.id))return res.status(400).json({error:"شناسه نامعتبر است"});const c=await Customer.findOne(ownFilter(req,req.params.id)).lean();if(!c)return res.status(404).json({error:"مشتری پیدا نشد"});const orders=await Order.find({customerId:c._id,ownerId:req.user._id}).sort({createdAt:-1}).lean();res.json({customer:c,orders:orders.map(o=>({...o,totals:orderTotals(o)}))})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/customers",auth,async(req,res)=>{try{if(!req.body.name?.trim())return res.status(400).json({error:"نام مشتری الزامی است"});const gender=req.body.gender==='female'?'female':'male';const measurements={};if(req.body.measurements?.[gender])measurements[gender]=req.body.measurements[gender];const c=await Customer.create({ownerId:req.user._id,name:req.body.name.trim(),phone:req.body.phone||"",address:req.body.address||"",gender,notes:req.body.notes||"",measurements});let order=null;if(req.body.order&&(req.body.order.description||req.body.order.price!=null))order=await Order.create({ownerId:req.user._id,customerId:c._id,description:req.body.order.description||"",price:Number(req.body.order.price||0),discount:Number(req.body.order.discount||0),initialPaid:Number(req.body.order.initialPaid||0),status:req.body.order.status||"registered",dueDate:req.body.order.dueDate||null,notes:req.body.order.notes||""});res.status(201).json({customer:c,order})}catch(e){res.status(500).json({error:e.message})}});
app.put("/api/customers/:id",auth,async(req,res)=>{try{if(!oid(req.params.id))return res.status(400).json({error:"شناسه نامعتبر است"});const c=await Customer.findOne(ownFilter(req,req.params.id));if(!c)return res.status(404).json({error:"مشتری پیدا نشد"});for(const k of ['name','phone','address','gender','notes'])if(req.body[k]!==undefined)c[k]=req.body[k];if(req.body.measurements){if(req.body.measurements.male)c.measurements.male=req.body.measurements.male;if(req.body.measurements.female)c.measurements.female=req.body.measurements.female}await c.save();res.json(c)}catch(e){res.status(500).json({error:e.message})}});
app.delete("/api/customers/:id",auth,async(req,res)=>{try{const c=await Customer.findOneAndDelete(ownFilter(req,req.params.id));if(!c)return res.status(404).json({error:"مشتری پیدا نشد"});await Order.deleteMany({customerId:c._id,ownerId:req.user._id});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/orders",auth,async(req,res)=>{try{const list=await Order.find({ownerId:req.user._id}).populate('customerId','name phone').sort({createdAt:-1}).lean();const q=(req.query.q||'').trim().toLowerCase();const out=list.map(o=>({...o,totals:orderTotals(o)}));res.json(q?out.filter(o=>(o.description||'').toLowerCase().includes(q)||(o.customerId?.name||'').toLowerCase().includes(q)||(o.customerId?.phone||'').includes(q)):out)}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/orders",auth,async(req,res)=>{try{if(!oid(req.body.customerId))return res.status(400).json({error:'مشتری نامعتبر است'});const c=await Customer.findOne({_id:req.body.customerId,ownerId:req.user._id});if(!c)return res.status(404).json({error:'مشتری متعلق به این حساب نیست'});const o=await Order.create({ownerId:req.user._id,customerId:c._id,description:req.body.description||'',price:Number(req.body.price||0),discount:Number(req.body.discount||0),initialPaid:Number(req.body.initialPaid||0),status:req.body.status||'registered',dueDate:req.body.dueDate||null,notes:req.body.notes||''});res.status(201).json({...o.toObject(),totals:orderTotals(o)})}catch(e){res.status(500).json({error:e.message})}});
app.put("/api/orders/:id",auth,async(req,res)=>{try{if(!oid(req.params.id))return res.status(400).json({error:'شناسه نامعتبر است'});const o=await Order.findOne(ownFilter(req,req.params.id));if(!o)return res.status(404).json({error:'سفارش پیدا نشد'});for(const k of ['description','status','dueDate','notes'])if(req.body[k]!==undefined)o[k]=req.body[k];for(const k of ['price','discount'])if(req.body[k]!==undefined)o[k]=Number(req.body[k]);await o.save();res.json({...o.toObject(),totals:orderTotals(o)})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/orders/:id/payments",auth,async(req,res)=>{try{if(!oid(req.params.id))return res.status(400).json({error:'شناسه نامعتبر است'});const o=await Order.findOne(ownFilter(req,req.params.id));if(!o)return res.status(404).json({error:'سفارش پیدا نشد'});const amount=Number(req.body.amount||0),t=orderTotals(o);if(amount<=0||amount>t.remaining)return res.status(400).json({error:amount<=0?'مبلغ نامعتبر است':'مبلغ بیشتر از باقی‌مانده است'});o.payments.push({amount,date:req.body.date||new Date(),note:req.body.note||''});await o.save();res.json({...o.toObject(),totals:orderTotals(o)})}catch(e){res.status(500).json({error:e.message})}});
app.delete("/api/orders/:id",auth,async(req,res)=>{try{const o=await Order.findOneAndDelete(ownFilter(req,req.params.id));if(!o)return res.status(404).json({error:'سفارش پیدا نشد'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

// Expenses
app.get("/api/expenses",auth,async(req,res)=>{try{res.json(await Expense.find({ownerId:req.user._id}).sort({date:-1}).lean())}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/expenses",auth,async(req,res)=>{try{const amount=Number(req.body.amount||0);if(amount<=0)return res.status(400).json({error:'مبلغ هزینه باید بیشتر از صفر باشد'});res.status(201).json(await Expense.create({ownerId:req.user._id,date:req.body.date||new Date(),type:req.body.type||'other',description:req.body.description||'',person:req.body.person||'',amount}))}catch(e){res.status(500).json({error:e.message})}});
app.put("/api/expenses/:id",auth,async(req,res)=>{try{const e=await Expense.findOneAndUpdate(ownFilter(req,req.params.id),{date:req.body.date,type:req.body.type,description:req.body.description||'',person:req.body.person||'',amount:Number(req.body.amount||0)},{new:true,runValidators:true});if(!e)return res.status(404).json({error:'هزینه پیدا نشد'});res.json(e)}catch(e){res.status(500).json({error:e.message})}});
app.delete("/api/expenses/:id",auth,async(req,res)=>{try{const e=await Expense.findOneAndDelete(ownFilter(req,req.params.id));if(!e)return res.status(404).json({error:'هزینه پیدا نشد'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

// Employees / payroll
app.get("/api/employees",auth,async(req,res)=>{try{const list=await Employee.find({ownerId:req.user._id}).sort({status:1,name:1}).lean();res.json(list.map(e=>({...e,payroll:employeePayroll(e)})))}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/employees",auth,async(req,res)=>{try{if(!req.body.name?.trim())return res.status(400).json({error:'نام کارمند الزامی است'});const e=await Employee.create({ownerId:req.user._id,name:req.body.name.trim(),phone:req.body.phone||'',task:req.body.task||'',monthlySalary:Number(req.body.monthlySalary||0),startDate:req.body.startDate||new Date(),status:req.body.status||'active',notes:req.body.notes||''});res.status(201).json({...e.toObject(),payroll:employeePayroll(e)})}catch(e){res.status(500).json({error:e.message})}});
app.put("/api/employees/:id",auth,async(req,res)=>{try{const e=await Employee.findOne(ownFilter(req,req.params.id));if(!e)return res.status(404).json({error:'کارمند پیدا نشد'});for(const k of ['name','phone','task','status','startDate','notes'])if(req.body[k]!==undefined)e[k]=req.body[k];if(req.body.monthlySalary!==undefined)e.monthlySalary=Number(req.body.monthlySalary);await e.save();res.json({...e.toObject(),payroll:employeePayroll(e)})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/employees/:id/payments",auth,async(req,res)=>{try{const e=await Employee.findOne(ownFilter(req,req.params.id));if(!e)return res.status(404).json({error:'کارمند پیدا نشد'});const amount=Number(req.body.amount||0),p=employeePayroll(e);if(amount<=0||amount>p.remaining)return res.status(400).json({error:amount<=0?'مبلغ نامعتبر است':'مبلغ بیشتر از باقی‌مانده حقوق این ماه است'});const payDate=req.body.date||new Date();e.payments.push({amount,date:payDate,note:req.body.note||''});await e.save();await Expense.create({ownerId:req.user._id,date:payDate,type:'salary',description:`پرداخت حقوق ${e.name}`,person:e.name,amount});res.json({...e.toObject(),payroll:employeePayroll(e)})}catch(e){res.status(500).json({error:e.message})}});
app.delete("/api/employees/:id",auth,async(req,res)=>{try{const e=await Employee.findOneAndDelete(ownFilter(req,req.params.id));if(!e)return res.status(404).json({error:'کارمند پیدا نشد'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

// Inventory
app.get("/api/inventory",auth,async(req,res)=>{try{const list=await Inventory.find({ownerId:req.user._id}).sort({name:1}).lean();res.json(list.map(i=>({...i,totalValue:inventoryValue(i),lowStock:Number(i.quantity)<=Number(i.minStock||0)})))}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/inventory",auth,async(req,res)=>{try{if(!req.body.name?.trim())return res.status(400).json({error:'نام کالا الزامی است'});const q=Math.max(0,Number(req.body.quantity||0));const i=await Inventory.create({ownerId:req.user._id,name:req.body.name.trim(),category:req.body.category||'سایر',quantity:q,unit:req.body.unit||'عدد',minStock:Number(req.body.minStock||0),unitPrice:Number(req.body.unitPrice||0),notes:req.body.notes||'',movements:q?[{type:'in',quantity:q,note:'موجودی اولیه'}]:[]});res.status(201).json({...i.toObject(),totalValue:inventoryValue(i),lowStock:i.quantity<=i.minStock})}catch(e){res.status(500).json({error:e.message})}});
app.put("/api/inventory/:id",auth,async(req,res)=>{try{const i=await Inventory.findOne(ownFilter(req,req.params.id));if(!i)return res.status(404).json({error:'کالا پیدا نشد'});for(const k of ['name','category','unit','notes'])if(req.body[k]!==undefined)i[k]=req.body[k];for(const k of ['minStock','unitPrice'])if(req.body[k]!==undefined)i[k]=Number(req.body[k]);await i.save();res.json({...i.toObject(),totalValue:inventoryValue(i),lowStock:i.quantity<=i.minStock})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/inventory/:id/movement",auth,async(req,res)=>{try{const i=await Inventory.findOne(ownFilter(req,req.params.id));if(!i)return res.status(404).json({error:'کالا پیدا نشد'});const type=req.body.type==='out'?'out':'in',q=Number(req.body.quantity||0);if(q<=0)return res.status(400).json({error:'مقدار نامعتبر است'});if(type==='out'&&q>i.quantity)return res.status(400).json({error:'موجودی کافی نیست'});i.quantity=type==='in'?i.quantity+q:i.quantity-q;i.movements.push({type,quantity:q,date:req.body.date||new Date(),note:req.body.note||''});await i.save();res.json({...i.toObject(),totalValue:inventoryValue(i),lowStock:i.quantity<=i.minStock})}catch(e){res.status(500).json({error:e.message})}});
app.delete("/api/inventory/:id",auth,async(req,res)=>{try{const i=await Inventory.findOneAndDelete(ownFilter(req,req.params.id));if(!i)return res.status(404).json({error:'کالا پیدا نشد'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.use(express.static(__dirname));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
async function start(){try{if(!MONGODB_URI)throw new Error('MONGODB_URI تنظیم نشده است');await mongoose.connect(MONGODB_URI);app.listen(PORT,()=>console.log(`Khayyat Yar Pro running on ${PORT}`))}catch(e){console.error(e.message);process.exit(1)}}
start();
